[build-system]
requires = [
    "setuptools",
    "wheel",
    "omnipath",
    "squidpy",
    "alphashape",
    "descartes",
    "cellpose",
    "shapely",
    "scikit-image",
    "pyitlib",
    "planktonspace"
]
build-backend = "setuptools.build_meta"
